import { chmod, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { appBundleIdentifier, appBundlePath } from "./paths.ts";
import { ensureDir, pathExists, removePath } from "./fs.ts";
import { HopperError } from "./errors.ts";

/**
 * A marker line embedded in every generated launcher. It lets us tell our
 * own bundles apart from an unrelated app that happens to share the name,
 * so install/remove never clobbers something we didn't create.
 */
function appMarker(profileName: string): string {
  return `claude-hopper-app: ${profileName}`;
}

export function isMacOS(): boolean {
  return process.platform === "darwin";
}

export function assertMacOS(action: string): void {
  if (!isMacOS()) {
    throw new HopperError(
      `${action} is only supported on macOS.`,
      "macOS .app bundles only make sense on macOS. On other platforms use the shell alias (`claude-<name>`) or `claude-hopper run <name>`.",
      "APP_NOT_MACOS",
    );
  }
}

export function infoPlist(profileName: string): string {
  const display = `Claude ${profileName}`;
  const id = appBundleIdentifier(profileName);
  // Profile names are validated to [A-Za-z0-9_-], so no XML metacharacters
  // can reach this template — direct interpolation is safe.
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
\t<key>CFBundleName</key>
\t<string>${display}</string>
\t<key>CFBundleDisplayName</key>
\t<string>${display}</string>
\t<key>CFBundleIdentifier</key>
\t<string>${id}</string>
\t<key>CFBundleVersion</key>
\t<string>1.0</string>
\t<key>CFBundleShortVersionString</key>
\t<string>1.0</string>
\t<key>CFBundlePackageType</key>
\t<string>APPL</string>
\t<key>CFBundleExecutable</key>
\t<string>launcher</string>
\t<key>CFBundleInfoDictionaryVersion</key>
\t<string>6.0</string>
\t<key>LSMinimumSystemVersion</key>
\t<string>10.13</string>
\t<key>NSHighResolutionCapable</key>
\t<true/>
</dict>
</plist>
`;
}

/**
 * The bundle's `Contents/MacOS/launcher`. Double-clicking the app runs this.
 *
 * It mirrors the shell alias exactly: set `CLAUDE_CONFIG_DIR` (via `$HOME`,
 * never a baked-in absolute path) and exec `claude`. The only extra step is
 * opening a Terminal window, because Claude Code is a terminal program and
 * Finder/Spotlight/Dock launches have no tty.
 *
 * The heredoc delimiter is single-quoted, so bash does NOT expand `$HOME`
 * here — it is passed literally into the AppleScript string and finally to
 * Terminal's own shell, which expands it on whatever machine runs the app.
 * That keeps the bundle portable and free of foreign absolute paths.
 */
export function launcherScript(profileName: string): string {
  return `#!/bin/bash
# ${appMarker(profileName)}
# Generated by claude-hopper. Do not edit by hand; re-run
# \`claude-hopper app install ${profileName}\` to regenerate.
#
# Equivalent to the shell alias:
#   CLAUDE_CONFIG_DIR="$HOME/.claude-hopper/profiles/${profileName}" command claude
osascript <<'APPLESCRIPT'
tell application "Terminal"
\tactivate
\tdo script "CLAUDE_CONFIG_DIR=\\"$HOME/.claude-hopper/profiles/${profileName}\\" command claude"
end tell
APPLESCRIPT
`;
}

async function isHopperApp(bundle: string, profileName: string): Promise<boolean> {
  const launcher = join(bundle, "Contents", "MacOS", "launcher");
  if (!(await pathExists(launcher))) return false;
  try {
    return (await readFile(launcher, "utf8")).includes(appMarker(profileName));
  } catch {
    return false;
  }
}

/**
 * Write (or refresh) the .app bundle for a profile. Pure file I/O — the
 * macOS-only UX guard lives in the command layer so this stays testable
 * everywhere, mirroring how `installAlias` is platform-agnostic.
 */
export async function installApp(
  profileName: string,
): Promise<{ path: string }> {
  const bundle = appBundlePath(profileName);

  if (await pathExists(bundle)) {
    if (!(await isHopperApp(bundle, profileName))) {
      throw new HopperError(
        `${bundle} already exists and was not created by claude-hopper.`,
        "Move or remove that app manually, then re-run.",
        "APP_FOREIGN_BUNDLE",
      );
    }
    // Idempotent refresh: wipe and rewrite so stale launchers can't linger.
    await removePath(bundle);
  }

  const contents = join(bundle, "Contents");
  const macos = join(contents, "MacOS");
  await ensureDir(macos);
  await ensureDir(join(contents, "Resources"));
  await writeFile(join(contents, "Info.plist"), infoPlist(profileName), "utf8");
  await writeFile(join(contents, "PkgInfo"), "APPL????", "utf8");
  const launcher = join(macos, "launcher");
  await writeFile(launcher, launcherScript(profileName), "utf8");
  await chmod(launcher, 0o755);

  return { path: bundle };
}

export async function removeApp(
  profileName: string,
): Promise<{ changed: boolean }> {
  const bundle = appBundlePath(profileName);
  if (!(await pathExists(bundle))) return { changed: false };
  if (!(await isHopperApp(bundle, profileName))) {
    throw new HopperError(
      `${bundle} was not created by claude-hopper — refusing to delete it.`,
      "Remove it manually if you really want it gone.",
      "APP_FOREIGN_BUNDLE",
    );
  }
  await removePath(bundle);
  return { changed: true };
}

export async function appInstalled(profileName: string): Promise<boolean> {
  const bundle = appBundlePath(profileName);
  if (!(await pathExists(bundle))) return false;
  return isHopperApp(bundle, profileName);
}
